name: "Debug and Release APK Publisher with mapping"
branding:
  icon: "package"
  color: "blue"
description: "Build & Publish Debug and Release APK on Github"
author: "adi-itgg"
inputs:
  GITHUB_TOKEN:
    required: true
    description: "Github secret token to allow automated publishing of APK to release."
  REPO_BRANCH:
    required: false
    description: "Github repository branch name."
runs:
  using: "docker"
  image: "Dockerfile"
